name          = "trees"
version       = "0.1.0"
author        = "Brian Shannan <brianshannan@gmail.com>"
description   = "Implementations of trees in Nim"
license       = "Apache 2.0"
srcDir        = "trees"
